src/Entity/Don.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;

use App\Repository\DonRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: DonRepository::class)]
class Don
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[Groups("dons")]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    #[Groups("dons")]
    #[Assert\NotBlank(message: "name is required")]
    private ?string $NameD = null;

    #[ORM\Column]
    #[Groups("dons")]
    #[Assert\NotBlank(message: "Quantity is required")]
    private ?int $quantite = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Groups("dons")]
    #[Assert\NotBlank(message: "Description is required")]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    #[Groups("dons")]
    #[Assert\NotBlank(message: "Localisation is required")]
    private ?string $Localisation = null;

    #[ORM\ManyToOne(inversedBy: 'Dons')]
    #[Groups("dons")]
    private ?CategoryD $categoryD = null;

    #[ORM\Column(length: 255)]
    #[Groups("dons")]
    #[Assert\NotBlank(message: "Please fill this Image")]
    private ?string $Image = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Email is required")]
    #[Groups("dons")]
    #[Assert\Email(message: "the email '{{ value }}'is not a valid email")]
    private ?string $email = null;


    #[ORM\Column]
    #[Assert\NotBlank(message: "Number is required")]
    #[Groups("dons")]
    #[Assert\Length(
        min: 8,
        max: 8,
        minMessage: 'Your Number must be at least {{ limit }} numbers long',
        maxMessage: 'Your  Number cannot be longer than {{ limit }} numbers',
    )]
    private ?int $Numero = null;

    #[ORM\ManyToOne(inversedBy: 'dons')]
    private ?User $user = null;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameD(): ?string
    {
        return $this->NameD;
    }

    public function setNameD(string $NameD): self
    {
        $this->NameD = $NameD;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->Localisation;
    }

    public function setLocalisation(string $Localisation): self
    {
        $this->Localisation = $Localisation;

        return $this;
    }

    public function getCategoryD(): ?CategoryD
    {
        return $this->categoryD;
    }

    public function setCategoryD(?CategoryD $categoryD): self
    {
        $this->categoryD = $categoryD;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNumero(): ?int
    {
        return $this->Numero;
    }

    public function setNumero(int $Numero): self
    {
        $this->Numero = $Numero;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/AnnonceCrudController.php
<?php

namespace App\Controller;

use App\Entity\Annonces;
use App\Entity\Commentaires;
use App\Form\AnnoncesType;
use App\Form\CommentairesType;
use  App\Form\SearchType;
use App\Repository\AnnoncesRepository;
use App\Repository\CommentairesRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
#use Doctrine\Common\Persistence\ObjectRepository;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

use function PHPUnit\Framework\stringContains;


// ************************** recherche **************************
#[Route('/annonce/crud')]
class AnnonceCrudController extends AbstractController
{
    #[Route("/Allannonce", name: 'list_annonces')]
    public function getannone(AnnoncesRepository $repo, NormalizerInterface $normalizer)
    {
        $annonce = $repo->findAll();
        $annonceNormalises = $normalizer->normalize($annonce, 'json', ['groups' => "annonce/crud"]);

        $json = json_encode($annonceNormalises);
        return new Response($json);
    }


    #[Route('/search', name: 'app_annonce_recherche')]
    public function index2(AnnoncesRepository $repo, Request $request): Response
    {

        $rec = $repo->findAll();
        $form = $this->createForm(SearchType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {

            $result = $repo->findByNom($form->getData());
            return $this->render(
                'annonce_crud/resultatRech.html.twig',
                array(

                    "resultOfSearch" => $result,


                )
            );
        }
        return $this->render('annonce_crud/search.html.twig', [

            "formSearch" => $form->createView()

        ]);
    }

    // **************************liste des annonces page d'accueil **************************

    #[Route('/', name: 'app_annonce_crud_index', methods: ['GET'])]
    public function index(AnnoncesRepository $annoncesRepository): Response
    {


        return $this->render('annonce_crud/index.html.twig', [
            'annonces' => $annoncesRepository->findAll(),
        ]);
    }


    // ******************affichage de la liste des annonces (back) **************************

    #[Route('/affichback', name: 'affichback', methods: ['GET'])]
    public function indexback(AnnoncesRepository $annoncesRepository): Response
    {


        return $this->render('annonce_crud/affichback.html.twig', [
            'annonces' => $annoncesRepository->findAll(),
        ]);
    }


    // ************************** liste des annonces **************************

    #[Route('/admin', name: 'app_annonce_crud_admin', methods: ['GET'])]
    public function admin(AnnoncesRepository $annoncesRepository): Response
    {
        return $this->render('annonce_crud/afficher.html.twig', [
            'annonces' => $annoncesRepository->findAll(),
        ]);
    }

    /* #[Route('/affich', name: 'app_affich', methods: ['GET'])]
    public function app_affich(AnnoncesRepository $annoncesRepository): Response
    {
        return $this->render('annonce_crud/affichage1.html.twig', ['annonces' => $annoncesRepository->findAll(),]);
    } */


    // **************************mobile **************************
   


    #[Route("/addAnnonceJSON", name: 'addAnnonceJson')]
    public function addannonce(Request $req, NormalizerInterface $normalizer)
    {
        $em = $this->getDoctrine()->getManager();
        $annonce = new Annonces();
        $annonce->setDescription($req->get('Description'));
        $annonce->setImage($req->get('Image'));
        //$annonce->setDatePublication((new \DateTime($req->get('DatePublication'))));
        $annonce->setadresse($req->get('adresse'));
        $em->persist($annonce);
        $em->flush();
        $jsonContent = $normalizer->normalize($annonce, 'json', ['groups' => "annonce/crud"]);
        return new Response(json_encode($jsonContent));
    }



    // ************************** Ajout **************************

    #[Route('/new', name: 'app_annonce_crud_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AnnoncesRepository $annoncesRepository, EntityManagerInterface $entityManager): Response
    {
        $annonce = new Annonces();
        $DateActuelle = new \DateTime('NOW');
        $formattedDate = $DateActuelle->format('Y-m-d H:i:s');
        $annonce->setDatePublication($formattedDate);
        $form = $this->createForm(AnnoncesType::class, $annonce);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($annonce);
            $entityManager->flush();

            /** @var UploadedFile $uploadedFile */
            $uploadedFile = $form['Image']->getData();
            $destination = 'C:\xampp\htdocs\public';
            $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
            $newFile = $originalFilename . '-' . uniqid() . '.' . $uploadedFile->guessExtension();
            $uploadedFile->move(
                $destination,
                $newFile
            );
            $annonce->setImage($newFile);
            $annonce->setNombreEtoiles(0);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($annonce);
            $entityManager->flush();
            $annoncesRepository->save($annonce, true);

            return $this->redirectToRoute('app_annonce_crud_index', [], Response::HTTP_SEE_OTHER);
        }



        return $this->renderForm('annonce_crud/new.html.twig', [
            'annonce' => $annonce,
            'form' => $form,
        ]);
    }

    // ************************** afficher une annonce (html) **************************

    #[Route('/{id}', name: 'app_annonce_crud_show', methods: ['GET'])]
    public function show(Annonces $annonce): Response
    {
        return $this->render('annonce_crud/show.html.twig', [
            'annonce' => $annonce,
        ]);
    }


    // ************************** afficher une annonce (Json) **************************

    #[Route("/annonce/{id}", name: 'annonce')]
    public function annonceId($id, NormalizerInterface $normalizer, AnnoncesRepository $repo)
    {
        $annonce = $repo->find($id);

        $annonceNormalises = $normalizer->normalize($annonce, 'json', ['groups' => "annonce/crud"]);
        return new Response(json_encode($annonceNormalises));
    }

    // ************************** update une annonce (Json) **************************

    #[Route("/UpdateAnnonceJSON/{id}", name: 'UpdateAnnonceJson_annonce_mobile',methods :['GET','POST'])]
    public function Updateannonce(Request $req, $id, NormalizerInterface $normalizer)
    {

        $em = $this->getDoctrine()->getManager();
        $annonce = $em->getRepository(Annonces::class)->find($id);

        $annonce->setDescription($req->get('Description'));
        $annonce->setImage($req->get('Image'));
       // $annonce->setDatePublication($req->get('DatePublication'));
        $annonce->setadresse($req->get('adresse'));

        $em->flush();
        $jsonContent = $normalizer->normalize($annonce, 'json', ['groups' => "annonce/crud"]);
        return new Response("Annonce updated successfully" . json_encode($jsonContent));
    }
    #[Route("/deleteannonceJSON/{id}", name: 'deleteannonceJson')]
    public function deleteannonce(Request $req, $id, NormalizerInterface $normalizer)
    {
        $em = $this->getDoctrine()->getManager();
        $annonce = $em->getRepository(Annonces::class)->find($id);
        $em->remove($annonce);
        $em->flush();
        $jsonContent = $normalizer->normalize($annonce, 'json', ['groups' => "annonce"]);
        return new Response("annonce deleted successfully" . json_encode($jsonContent));
    }

    // ************************** supprimer reponse **************************

    #[Route('/delete/{id}', name: 'app_commentaire_delete', methods: ['POST'])]
    // #[Route('/{id}', name: 'app_annonce_crud_delete', methods: ['DELETE'])]
    public function deleteCommentaire(Request $request, Commentaires $commentaires, CommentairesRepository $commentairesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $commentaires->getId(), $request->request->get('_token'))) {
            $commentairesRepository->remove($commentaires, true);
        }

        return $this->redirectToRoute('app_annonce_crud_index', [], Response::HTTP_SEE_OTHER);
    }

    // ************************** modifier une annonce **************************

    #[Route('/{id}/edit', name: 'app_annonce_crud_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Annonces $annonce, AnnoncesRepository $annoncesRepository): Response
    {
        $form = $this->createForm(AnnoncesType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $annoncesRepository->save($annonce, true);
            /** @var UploadedFile $uploadedFile */
            $uploadedFile = $form['Image']->getData();
            $destination = $this->getParameter('kernel.project_dir') . '/public/uploads';
            $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
            $newFilename = $originalFilename . '-' . uniqid() . '.' . $uploadedFile->guessExtension();
            $uploadedFile->move(
                $destination,
                $newFilename
            );
            $annonce->setImage($newFilename);

            $this->getDoctrine()->getManager()->flush();

templates/annonce_crud/_delete_form.html.twig
<form method="post" action="{{ path('app_annonce_crud_delete', {'id': annonce.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ annonce.id) }}">
    <button class="btn btn-outline-danger">Delete</button>
</form>

templates/annonce_crud/_form.html.twig
{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}
<center >

{% form_theme form 'bootstrap_5_horizontal_layout.html.twig' %} 

    <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>
    <div class="col-lg-7">
        {{ form_row(form.Description) }}
    </div> 
    <div class="col-lg-7">
        {{ form_row(form.Image) }}
    </div>
    <div class="col-lg-7">
        {{ form_row(form.adresse) }}
    </div>
    <div class="col-lg-7">
        {{ form_row(form.Categorie) }}
    </div>
    
    
    
   
    
   
        <button class="btn btn-outline-success" >{{ button_label|default('Save') }}</button>
         <a href="{{ path('app_annonce_crud_index') }}"><input type="button" class="btn btn-outline-success" value="retour"</a>
       
{{ form_end(form) }}

</center>

templates/annonce_crud/affichback.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Annonces index{% endblock %}

{% block body %}
  



    <div class="container-xxl py-5">
        <div class="container p-5 my-5 "  >
            <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" >
                <div class="d-inline-block rounded-pill bg-secondary text-primary py-1 px-3 mb-3">♥</div>
                <h1 class="display-6 mb-5">Les annonces</h1>
            </div>
             
            <div class="row g-4 " style="display:inline-block;justify-content:center;" data-wow-delay="0.7s" >
                           {% for annonce in annonces %}

                <div class="col-lg-3 col-md-5 wow fadeInUp"  style=" display: inline-block;justify-content:right;"    >
                    <div class="team-item position-relative rounded overflow-hidden">
                   
                        <div class="overflow-hidden">
                         
                            <img class="img-fluid" src="/uploads/{{ annonce.image }}"  >
                            
                             
                        </div>
                        <div class="team-text bg-light text-center p-4">
                      
                           {#  <h5>{{ evenement.NomEvent }}</h5> #}
                            
                            <p class="text-primary">{{ annonce.description }}</p>
                            
                            <div class="team-social text-center">
                            
                           
                           
                            <td><a href="{{ path('app_annonce_crud_show', {'id': annonce.id}) }}"><input type="button" class="btn btn-outline-success" value="afficher"</a></td>
                           </div>
                            
                            
                        </div>
                    </div>
                  
                </div>
             
              {% endfor %}
            </div>
            
         </div>

    </div>

<a href="{{ path('app_annonce_recherche') }}"><button type="button" class="btn btn-outline-success" >Recherche</button></a>
<a href="{{ path('app_categorie_index') }}">back to list</a>


    <a href="/categorie">Create Categorie</a>
    <div class="grix xs2 sm3 gutter-0 card">
			<div class="col-xs2 col-sm3">
				<center>
                {#      <h2><i> Liste des commentaires </i></h2>
                </center>
                {% for commentaire in annonce.commentaires %}
                   {% if commentaire.parent == null %}
                       <h4>commentaire de {{commentaire.pseudo}}</h4>
                       <p>Publié le {{commentaire.dateCreation|date("d/m/Y H:i:s")}}</p>
                       <div>{{commentaire.contenu|raw}}</div>
                       <p><a href="#ajout-commentaire" data-reply data-id="{{commentaire.id}}" class="btn btn-outline-success">Répondre</a></p> #}



{% endblock %}

templates/annonce_crud/afficher.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Annonces index{% endblock %}


{% block body %}
    <h1>Annonces index</h1>

    <table class="table">
        <thead>
            <tr>
                {# <th>Id</th> #}
                <th>Description</th>
                <th>Image</th>
                <th>adresse</th>
                <th>Date de publication</th>
                <th>Categorie</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>

        {% for annonce in annonces %}
            <tr>
                {# <td>{{ annonce.id }}</td> #}
                <td>{{ annonce.Description }}</td>
                <td><img src="/uploads/{{ annonce.image }}" alt="Pas d'image" width="100" height="100"></td>
                <td>{{ annonce.adresse }}</td>
                <td>{{ annonce.DatePublication }}</td>
                <td>{{ annonce.categorie.nom }}</td>
                <td>
                <a href="{{ path('app_annonce_crud_delete') }}"><button type="button" class="btn btn-outline-danger" >Supprimer</button></a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    
    <a href="{{ path('app_categorie_index') }}">Back</a>

    
    
{% endblock %}

templates/annonce_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonces{% endblock %}

{% block body %}
  
<link rel="stylesheet" href="{{ asset('css/test.css') }}">


  
  <div class="container">
  <h1>Annonces</h1>
  <div class="row">
    <div class="col-md-8">
      <ul class="cards">
        {% for annonce in annonces %}
        <li class="cards_item">
          <div class="card">
            <div class="img">
              <a href="{{ path('app_annonce_crud_show', {'id': annonce.id}) }}">
                <img src="http://localhost/public/{{ annonce.image }}" width="500" height="300">
              </a>
            </div> 
            <div class="card_content">
              <h2 class="card_title"></h2>
              <p class="card_text">{{ annonce.description }}</p>
              <a href="{{ path('app_annonce_crud_show', {'id': annonce.id}) }}">
								<button type="button" class="btn card_btn">Afficher</button>
							</a>
            </div> 
          </div>
        </li>
        {% endfor %}
      </ul>
    
    </div>
    <div class="col-md-4">
      <div class="mb-3">
        <a href="{{ path('app_annonce_crud_new') }}">
          <input type="button" class="btn btn-outline-success" value="Nouvelle annonce">
        </a>
      </div>
      <div class="mb-3">
        <a href="{{ path('app_annonce_recherche') }}">
          <input type="button" class="btn btn-outline-success" value="Recherche">
        </a>
      </div>
      <div class="mb-3">
        {% if is_granted('ROLE_ADMIN') %}
    <a href="/categorie">Create Categorie</a>
    {% endif %}
      </div>
      
    </div>
  </div>
</div>


    
   
                {#      <h2><i> Liste des commentaires </i></h2>
                </center>
                {% for commentaire in annonce.commentaires %}
                   {% if commentaire.parent == null %}
                       <h4>commentaire de {{commentaire.pseudo}}</h4>
                       <p>Publié le {{commentaire.dateCreation|date("d/m/Y H:i:s")}}</p>
                       <div>{{commentaire.contenu|raw}}</div>
                       <p><a href="#ajout-commentaire" data-reply data-id="{{commentaire.id}}" class="btn btn-outline-success">Répondre</a></p> #}
{# 
<div class="rating">
  <input type="radio" id="star5" name="rating" value="5" />
  <label for="star5" title="Excellent">5 étoiles</label>
  <input type="radio" id="star4" name="rating" value="4" />
  <label for="star4" title="Très bien">4 étoiles</label>
  <input type="radio" id="star3" name="rating" value="3" />
  <label for="star3" title="Bien">3 étoiles</label>
  <input type="radio" id="star2" name="rating" value="2" />
  <label for="star2" title="Moyen">2 étoiles</label>
  <input type="radio" id="star1" name="rating" value="1" />
  <label for="star1" title="Mauvais">1 étoile</label>
</div>

 #}


{% endblock %}

templates/annonce_crud/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Annonces{% endblock %}

{% block body %}
    <h1>Create new Annonces</h1>

    {{ include('annonce_crud/_form.html.twig') }}

{% endblock %}

templates/annonce_crud/resultatRech.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonces index{% endblock %}

{% block body %}
  



    <div class="container-xxl py-5">
        <div class="container p-5 my-5 "  >
            <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" >
                <div class="d-inline-block rounded-pill bg-secondary text-primary py-1 px-3 mb-3">♥</div>
                <h1 class="display-6 mb-5">Les annonces</h1>
            </div>
             
            <div class="row g-4 " style="display:inline-block;justify-content:center;" data-wow-delay="0.7s" >
                           {% for annonce in resultOfSearch %}

                <div class="col-lg-3 col-md-5 wow fadeInUp"  style=" display: inline-block;justify-content:right;"    >
                    <div class="team-item position-relative rounded overflow-hidden">
                        <div class="overflow-hidden">
                         
                            <img class="img-fluid" src="/uploads/{{ annonce.image }}"  >
                             
                        </div>
                        <div class="team-text bg-light text-center p-4">
                      
                           {#  <h5>{{ evenement.NomEvent }}</h5> #}
                            
                            <p class="text-primary">{{ annonce.description }}</p>
                            
                            <div class="team-social text-center">
                            
                           
                           
                            <td><a href="{{ path('app_annonce_crud_show', {'id': annonce.id}) }}"><input type="button" class="btn btn-outline-success" value="afficher"</a></td>
                           
                           

                            </div>
                        </div>
                    </div>
                  
                </div>
             
              {% endfor %}
            </div>
         </div>

    </div>

    {% endblock %}

templates/annonce_crud/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonces{% endblock %}

{% block stylesheet %}

<!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Saira:wght@500;600;700&display=swap" rel="stylesheet"> 

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{{asset('lib/animate/animate.min.css')}}" rel="stylesheet">
    <link href="{{asset('lib/owlcarousel/assets/owl.carousel.min.css')}}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{{asset('css/style.css')}}" rel="stylesheet">
    <link href="{{asset('css/rating.css')}}" rel="stylesheet">
    <link href="{{asset('css/rating.js')}}" rel="stylesheet">
      <style>
        .star {
            font-size: 1.5rem;
        }
        
        .hover {
            color: rgb(255, 196, 0);
        }
    </style>

{% endblock %}

{% block body %}
    <h1>Annonces</h1>

    <table class="table">
        <tbody>
           {#  <tr>
                <th>Id</th>
                <td>{{ annonce.id }}</td>
            </tr> #}
            
            <tr>
                <th>Description</th>
                <td>{{ annonce.Description }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td><img src="/uploads/{{ annonce.image }}" alt="Pas d'image" width="100" height="100"></td>
            </tr>
            
             <tr>
                <th>adresse</th>
                <td>{{ annonce.adresse }}</td>
            </tr>
            <tr>
            <p>Date de publication : {{ annonce.DatePublication|date('Y-m-d H:i:s') }}</p>    
            </tr>
            <tr>
            <p>Categorie : {{ annonce.categorie.nom }}</p>    
            </tr>
            <tr>
            <p>Nombre Etoile : {{ annonce.nombreEtoiles }}</p>    
            </tr>
            <tr>
           <a href="{{ path('app_otheruser',{'id': annonce.user.id}) }}"><button type="button" class="btn btn-outline-success" >Profil</button></a>
            </tr>
            

        </tbody>
    </table>
    
    {% if app.user.id != annonce.rated %}
    
    <i class="star" data-note="1">&#9733;</i>
    <i class="star" data-note="2">&#9733;</i>
    <i class="star" data-note="3">&#9733;</i>
    <i class="star" data-note="4">&#9733;</i>
    <i class="star" data-note="5">&#9733;</i>
    <i class="note">Note:</i>
    {% endif %}
    <script>
        const stars = document.querySelectorAll('.star');
        let check = false;
        stars.forEach(star => {
            star.addEventListener('mouseover', selectStars);
            star.addEventListener('mouseleave', unselectStars);
            star.addEventListener('click', activeSelect);
        })

        function selectStars(e) {
            const data = e.target;
            const etoiles = priviousSiblings(data);
            if (!check) {
                etoiles.forEach(etoile => {
                    etoile.classList.add('hover');
                })
            }

        }

        function unselectStars(e) {
            const data = e.target;
            const etoiles = priviousSiblings(data);
            if (!check) {
                etoiles.forEach(etoile => {
                    etoile.classList.remove('hover');
                })
            }
        }

        function activeSelect(e) {
            if (!check) {
               
                    console.log("*************************************************");
                check = true;
                document.querySelector('.note').innerHTML = 'Note ' + e.target.dataset.note;
                window.location.href = "/rating?id=" + {{ annonce.id|json_encode() }} + "&note_value=" + e.target.dataset.note +"&userid=" + {{ app.user.id|json_encode() }};
                
            }
        }

        function priviousSiblings(data) {
            let values = [data];
            while (data = data.previousSibling) {
                if (data.nodeName === 'I') {
                    values.push(data);
                }
            }
            return values;
        }
    </script>
<a href="{{ path('app_annonce_crud_index') }}"><button type="button" class="btn btn-outline-success" >Retour</button></a>
<a href="{{ path('app_annonce_crud_edit', {'id': annonce.id}) }}"><button type="button" class="btn btn-outline-success" >Modifier</button></a>
<a href="{{ path('detail', {'id': annonce.id}) }}"><button type="button" class="btn btn-secondary">Detail</button></a>
<a href="{{ path('show_map2', {'id': annonce.id}) }}"><button type="button" class="btn btn-secondary">Map</button></a>

    

    {{ include('annonce_crud/_delete_form.html.twig') }}
{% endblock %}